name: Publish to NPM
env:
  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
  NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
'on':
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: '${{ env.STORE_PATH }}'
          key: '${{ runner.os }}-pnpm-store-${{ hashFiles(''**/pnpm-lock.yaml'') }}'
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Bump version
        run: pnpm changeset version
      - name: PR or Publish
        id: changesets
        uses: changesets/action@v1.4.5
        with:
          token: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          version: pnpm changeset:version
          publish: pnpm changeset:publish
      - name: Publish Prerelease
        if: steps.changesets.outputs.published != 'true'
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
          git reset --hard origin/main
          pnpm changeset version --no-git-tag --snapshot canary
          pnpm changeset publish --no-git-tag --snapshot canary --tag canary
