name: Publish to NPM

on:
  push:
    branches:
      - actions

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      id-token: write
      issues: write
      repository-projects: write
      deployments: write
      packages: write
      pull-requests: write
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # or your preferred version

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
        version: 8
        run_install: false

    - name: Install Dependencies
      run: pnpm install

    - name: Build
      run: pnpm run build # replace with your build command if different

    - name: Publish to NPM
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        npm config set "//registry.npmjs.org/:_authToken" "$NPM_TOKEN"
        pnpm publish --access public

